/*
 * Copyright 2014 Pawan Dubey (pawandubey@outlook.com)
 * 
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package com.pawandubey.texus;

import com.pawandubey.texus.actions.AboutAction;
import com.pawandubey.texus.actions.NewAction;
import com.pawandubey.texus.actions.OpenAction;
import com.pawandubey.texus.actions.SaveAction;
import javax.swing.ActionMap;
import javax.swing.JButton;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;
import javax.swing.JToolBar;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.text.DefaultEditorKit;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Pawan Dubey <pawandubey@outlook.com>
 */
public class Texus extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L;

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    /**
     * Creates new form Texus
     */
    public Texus() {
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content
     * of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollpane = new javax.swing.JScrollPane();
        editor = new javax.swing.JTextPane();
        toolbar = new javax.swing.JToolBar();
        newTool = new javax.swing.JButton();
        openTool = new javax.swing.JButton();
        saveTool = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        cutTool = new javax.swing.JButton();
        copyTool = new javax.swing.JButton();
        pasteTool = new javax.swing.JButton();
        menubar = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        newfile = new javax.swing.JMenuItem();
        open = new javax.swing.JMenuItem();
        save = new javax.swing.JMenuItem();
        saveas = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        edit = new javax.swing.JMenu();
        cut = new javax.swing.JMenuItem();
        copy = new javax.swing.JMenuItem();
        paste = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Texus");
        setName("window"); // NOI18N
        setPreferredSize(new java.awt.Dimension(960, 540));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        editor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                editorKeyTyped(evt);
            }
        });
        scrollpane.setViewportView(editor);

        toolbar.setFloatable(false);
        toolbar.setRollover(true);

        newTool.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mahe\\Downloads\\PNG\\32\\Gnome-Document-New-32.png")); // NOI18N
        newTool.setBorderPainted(false);
        newTool.setFocusable(false);
        newTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newTool.setOpaque(false);
        newTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(newTool);

        openTool.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mahe\\Downloads\\PNG\\32\\Gnome-Document-Open-32.png")); // NOI18N
        openTool.setBorderPainted(false);
        openTool.setFocusable(false);
        openTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openTool.setOpaque(false);
        openTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(openTool);

        saveTool.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mahe\\Downloads\\PNG\\32\\Gnome-Document-Save-32.png")); // NOI18N
        saveTool.setBorderPainted(false);
        saveTool.setEnabled(false);
        saveTool.setFocusable(false);
        saveTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveTool.setOpaque(false);
        saveTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(saveTool);

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator1.setSeparatorSize(new java.awt.Dimension(10, 50));
        toolbar.add(jSeparator1);

        cutTool.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mahe\\Downloads\\PNG\\32\\Gnome-Edit-Cut-32.png")); // NOI18N
        cutTool.setBorderPainted(false);
        cutTool.setFocusable(false);
        cutTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cutTool.setOpaque(false);
        cutTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(cutTool);

        copyTool.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mahe\\Downloads\\PNG\\32\\Gnome-Edit-Copy-32.png")); // NOI18N
        copyTool.setBorderPainted(false);
        copyTool.setFocusable(false);
        copyTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        copyTool.setOpaque(false);
        copyTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(copyTool);

        pasteTool.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mahe\\Downloads\\PNG\\32\\Gnome-Edit-Paste-32.png")); // NOI18N
        pasteTool.setBorderPainted(false);
        pasteTool.setFocusable(false);
        pasteTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pasteTool.setOpaque(false);
        pasteTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolbar.add(pasteTool);

        file.setText("File");

        newfile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cc/black/png/doc_empty_icon&16.png"))); // NOI18N
        newfile.setText("New");
        file.add(newfile);

        open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cc/black/png/folder_open_icon&16.png"))); // NOI18N
        open.setText("Open");
        file.add(open);

        save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cc/black/png/save_icon&16.png"))); // NOI18N
        save.setText("Save");
        save.setEnabled(false);
        file.add(save);

        saveas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        saveas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cc/black/png/save_icon&16.png"))); // NOI18N
        saveas.setText("Save As");
        saveas.setEnabled(false);
        file.add(saveas);

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cc/black/png/app_window_cross_icon&16.png"))); // NOI18N
        exit.setText("Exit");
        file.add(exit);

        menubar.add(file);

        edit.setText("Edit");

        cut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        cut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cc/black/png/clipboard_cut_icon&16.png"))); // NOI18N
        cut.setText("Cut");
        edit.add(cut);

        copy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        copy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cc/black/png/clipboard_copy_icon&16.png"))); // NOI18N
        copy.setText("Copy");
        edit.add(copy);

        paste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        paste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cc/black/png/clipboard_past_icon&16.png"))); // NOI18N
        paste.setText("Paste");
        edit.add(paste);

        menubar.add(edit);

        help.setText("Help");

        about.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cc/black/png/info_icon&16.png"))); // NOI18N
        about.setText("About");
        help.add(about);

        menubar.add(help);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolbar, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollpane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(toolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpane, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editorKeyTyped
        getSave().setEnabled(true);
        getSavetool().setEnabled(true);
        getSaveas().setEnabled(true);
    }//GEN-LAST:event_editorKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setActionMap(this.getEditor().getActionMap());
        
        getSaveaction().setTexus(this);
        getOpenaction().setTexus(this);
        
        about.addActionListener(aboutaction);
            
        getSave().addActionListener(getSaveaction());
        getSavetool().addActionListener(getSaveaction());
        getOpen().addActionListener(getOpenaction());
        getOpentool().addActionListener(getOpenaction());
        getNewfile().addActionListener(getNewaction());
        getNewtool().addActionListener(getNewaction());
        getCut().addActionListener(getActionMap().get(DefaultEditorKit.cutAction));
        getCuttool().addActionListener(getActionMap().get(DefaultEditorKit.cutAction));
        getCopy().addActionListener(getActionMap().get(DefaultEditorKit.copyAction));
        getCopytool().addActionListener(getActionMap().get(DefaultEditorKit.copyAction));
        getPaste().addActionListener(getActionMap().get(DefaultEditorKit.pasteAction));
        getPastetool().addActionListener(getActionMap().get(DefaultEditorKit.pasteAction));
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel("org.pushingpixels.substance.api.skin.SubstanceGraphiteLookAndFeel");
        }
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Texus().setVisible(true);
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about;
    private javax.swing.JMenuItem copy;
    private javax.swing.JButton copyTool;
    private javax.swing.JMenuItem cut;
    private javax.swing.JButton cutTool;
    private javax.swing.JMenu edit;
    private javax.swing.JTextPane editor;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu file;
    private javax.swing.JMenu help;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JButton newTool;
    private javax.swing.JMenuItem newfile;
    private javax.swing.JMenuItem open;
    private javax.swing.JButton openTool;
    private javax.swing.JMenuItem paste;
    private javax.swing.JButton pasteTool;
    private javax.swing.JMenuItem save;
    private javax.swing.JButton saveTool;
    private javax.swing.JMenuItem saveas;
    private javax.swing.JScrollPane scrollpane;
    private javax.swing.JToolBar toolbar;
    // End of variables declaration//GEN-END:variables
    private ActionMap actionMap;
    private final SaveAction saveaction = new SaveAction();
    private final OpenAction openaction = new OpenAction();
    private final NewAction newaction = new NewAction();
    private final AboutAction aboutaction = new AboutAction();
    
    public JTextPane getEditor(){
        return this.editor;
    }

    public JMenuItem getAbout() {
        return about;
    }

    public void setAbout(JMenuItem about) {
        this.about = about;
    }

    public JMenuItem getCopy() {
        return copy;
    }

    public void setCopy(JMenuItem copy) {
        this.copy = copy;
    }

    public JButton getCopytool() {
        return copyTool;
    }

    public void setCopytool(JButton copytool) {
        this.copyTool = copytool;
    }

    public JMenuItem getCut() {
        return cut;
    }

    public void setCut(JMenuItem cut) {
        this.cut = cut;
    }

    public JButton getCuttool() {
        return cutTool;
    }

    public void setCuttool(JButton cuttool) {
        this.cutTool = cuttool;
    }

    public JMenu getEdit() {
        return edit;
    }

    public void setEdit(JMenu edit) {
        this.edit = edit;
    }

    public void setEditor(JTextPane editor) {
        this.editor = editor;
    }

    public JMenuItem getExit() {
        return exit;
    }

    public void setExit(JMenuItem exit) {
        this.exit = exit;
    }

    public JMenu getFile() {
        return file;
    }

    public void setFile(JMenu file) {
        this.file = file;
    }

    public JMenu getHelp() {
        return help;
    }

    public void setHelp(JMenu help) {
        this.help = help;
    }

    public JMenuBar getMenubar() {
        return menubar;
    }

    public void setMenubar(JMenuBar menubar) {
        this.menubar = menubar;
    }

    public JMenuItem getNewfile() {
        return newfile;
    }

    public void setNewfile(JMenuItem newfile) {
        this.newfile = newfile;
    }

    public JButton getNewtool() {
        return newTool;
    }

    public void setNewtool(JButton newtool) {
        this.newTool = newtool;
    }

    public JMenuItem getOpen() {
        return open;
    }

    public void setOpen(JMenuItem open) {
        this.open = open;
    }

    public JButton getOpentool() {
        return openTool;
    }

    public void setOpentool(JButton opentool) {
        this.openTool = opentool;
    }

    public JMenuItem getPaste() {
        return paste;
    }

    public void setPaste(JMenuItem paste) {
        this.paste = paste;
    }

    public JButton getPastetool() {
        return pasteTool;
    }

    public void setPastetool(JButton pastetool) {
        this.pasteTool = pastetool;
    }

    public JMenuItem getSave() {
        return save;
    }

    public void setSave(JMenuItem save) {
        this.save = save;
    }

    public JMenuItem getSaveas() {
        return saveas;
    }

    public void setSaveas(JMenuItem saveas) {
        this.saveas = saveas;
    }

    public JButton getSavetool() {
        return saveTool;
    }

    public void setSavetool(JButton savetool) {
        this.saveTool = savetool;
    }

    public JScrollPane getScrollpane() {
        return scrollpane;
    }

    public void setScrollpane(JScrollPane scrollpane) {
        this.scrollpane = scrollpane;
    }

    public JToolBar getToolbar() {
        return toolbar;
    }

    public void setToolbar(JToolBar toolbar) {
        this.toolbar = toolbar;
    }

    public ActionMap getActionMap() {
        return actionMap;
    }

    public void setActionMap(ActionMap actionMap) {
        this.actionMap = actionMap;
    }

    public SaveAction getSaveaction() {
        return saveaction;
    }

    public OpenAction getOpenaction() {
        return openaction;
    }

    public NewAction getNewaction() {
        return newaction;
    }
    
    
}
